service:
  port: 3000
  auth:
    username: admin
    password: 123qwe
  jwt:
    salt: verifydifficult
targets:
  cluster01:
    bigip01:
      address: https://10.3.0.11
      username: admin
      password: 123qwe
    bigip02:
      address: https://10.3.0.12
      username: admin
      password: 123qwe